Logical/full upgrade
sonr-io/blockchain pull request #11
Opened 2022-04-07 17:55 UTC by prnk28

Decided to mess around and go bananas lol

### Added

- New registry module type `Session`

  - Contains metadata for `WhoIs`, `BaseDID`, and active `Credential`.
  - Utilized to verify current user and interact with other modules
  - Interfaces over Webauthn package
  - Generates New DID's based on underlying DID from `WhoIs`

- Added Module Specific Documentation for all x/{module} folders

  - Begun Status code table
  - Provided implemented method overview and reference
  - Provide Module record description

- Implemented business logic for the following methods

  - `RegisterApplication()`
  - `AccessApplication()`
  - `CreateObject()`
  - `CreateChannel()`
  - `CreateBucket()`

### Removed

- Removed `x/blob` module for less complex Document structure
- Removed Peer type definition from `x/registry`
- Removed ServiceConfig type definition from `x/registry`

### Changed

- Updated Module record key value

  - All `x/{module}` modules now utilize DIDs as the key value
  - Querying individual records now fully utilizes DIDs

- Added **Session** to all `x/{module}` modules transaction messages
- Upgraded Object to utilize Transformation methods to allow for more complex data structures
- Modified **CUD** Messages to utilized Record for each module specific storage

2022-04-07 19:31 UTC, prnk28 commented
### Additional Changes

- Added TaskFile commands for `Serve`, `Start`, `Build`, and `Clean`
- Removed Buf.Build configuration from all proto

2022-04-08 00:01 UTC, mcjcloud requested changes

2022-04-08 00:25 UTC, prnk28 commented on proto/bucket/tx.proto
> +  repeated sonrio.sonr.object.ObjectDoc added_objects = 5;
Smart thinking

2022-04-08 00:30 UTC, prnk28 commented on proto/bucket/tx.proto
>  message MsgReadBucket {
Removing all read methods from buckets objects and channels - because query does the same thing. Going to update query request to contain Session

2022-04-08 00:31 UTC, prnk28 commented on proto/bucket/tx.proto
> +  repeated sonrio.sonr.object.ObjectDoc added_objects = 5;
Yes agreed

2022-04-08 00:35 UTC, joshLong145 reviewed
left some comments on the proto definitions

2022-04-08 00:35 UTC, joshLong145 commented on proto/bucket/tx.proto
> +  repeated sonrio.sonr.object.ObjectDoc added_objects = 5;
still think we need the session such that we can confirm the action is valid. but i think i agree that DID and `Session` are needed

2022-04-08 00:35 UTC, joshLong145 commented on proto/bucket/tx.proto
> +    WhichIs which_is = 3;
Do we need `Session` instance here for this operation?

2022-04-08 00:35 UTC, joshLong145 commented on proto/channel/tx.proto
> +  HowIs how_is = 3;
do we want a `Session` instance here as well to validate session state on message. it might be mute at this point but could be useful

2022-04-08 00:35 UTC, joshLong145 commented on proto/channel/tx.proto
>    string creator = 1;
the session i dont think needs to contain the did, that is a separate response

2022-04-08 00:35 UTC, joshLong145 commented on proto/object/tx.proto
> +
do we also need Session i the response on the read operation?

2022-04-08 00:35 UTC, joshLong145 commented on proto/object/tx.proto
> +
do we also need Session i the response on the read operation?

2022-04-08 00:35 UTC, joshLong145 commented on proto/registry/tx.proto
> +  map<string, string> metadata = 4; // optional
we might want to use a more descriptive name here describing the domain of the metadata if possible

2022-04-08 00:35 UTC, joshLong145 commented on proto/registry/who_is.proto
> +	string base_did = 1;
i think `base_did` should be optional unless this is the domain name non transformed into its did schema.

2022-04-08 00:44 UTC, mcjcloud commented on proto/registry/who_is.proto
> +	string base_did = 1;
I think all fields in proto3 are optional by default

2022-04-08 03:14 UTC, Peyton232 commented on proto/registry/who_is.proto
> +	string base_did = 1;
"We dropped required fields in proto3 because required fields are generally considered harmful and violating protobuf's compatibility semantics. The whole idea of using protobuf is that it allows you to add/remove fields from your protocol definition while still being fully forward/backward compatible with newer/older binaries. Required fields break this though. You can never safely add a required field to a .proto definition, nor can you safely remove an existing required field because both of these actions break wire compatibility. For example, if you add a required field to a .proto definition, binaries built with the new definition won't be able to parse data serialized using the old definition because the required field is not present in old data. In a complex system where .proto definitions are shared widely across many different components of the system, adding/removing required fields could easily bring down multiple parts of the system. We have seen production issues caused by this multiple times and it's pretty much banned everywhere inside Google for anyone to add/remove required fields. For this reason we completely removed required fields in proto3.

After the removal of "required", "optional" is just redundant so we removed "optional" as well."
https://github.com/protocolbuffers/protobuf/issues/2497

2022-04-08 03:14 UTC, Peyton232 commented on proto/registry/who_is.proto
> +	string base_did = 1;
all fields are optional by default in proto3 and you can't have required fields

2022-04-08 03:14 UTC, Peyton232 commented on proto/registry/who_is.proto
> +	string base_did = 1;
"We dropped required fields in proto3 because required fields are generally considered harmful and violating protobuf's compatibility semantics. The whole idea of using protobuf is that it allows you to add/remove fields from your protocol definition while still being fully forward/backward compatible with newer/older binaries. Required fields break this though. You can never safely add a required field to a .proto definition, nor can you safely remove an existing required field because both of these actions break wire compatibility. For example, if you add a required field to a .proto definition, binaries built with the new definition won't be able to parse data serialized using the old definition because the required field is not present in old data. In a complex system where .proto definitions are shared widely across many different components of the system, adding/removing required fields could easily bring down multiple parts of the system. We have seen production issues caused by this multiple times and it's pretty much banned everywhere inside Google for anyone to add/remove required fields. For this reason we completely removed required fields in proto3.

After the removal of "required", "optional" is just redundant so we removed "optional" as well."

https://github.com/protocolbuffers/protobuf/issues/2497

2022-04-08 03:14 UTC, Peyton232 commented on proto/registry/tx.proto
>  message MsgUpdateName {
Do we not need session for MsgUpdateName?

2022-04-08 03:14 UTC, Peyton232 commented on proto/registry/tx.proto
> +  map<string, string> metadata = 4; // optional
I think the generic approach of jus "metadata" is fine unless we forsee specific obvious use cases

2022-04-08 03:14 UTC, Peyton232 commented on proto/bucket/which_is.proto
>    // Document is the DID Document of the registered name and account encoded as JSON
This comment, and the one in what_is and who_is should be updated

2022-04-08 03:14 UTC, Peyton232 commented on proto/channel/tx.proto
>  message MsgCreateHowIsResponse {}
no response?

2022-04-08 14:55 UTC, prnk28 commented on proto/bucket/tx.proto
>    string creator = 1;
Yes starport created field

2022-04-08 14:57 UTC, prnk28 commented
Removed the read method transaction and slapped session into the Query request on all modules

2022-04-08 15:01 UTC, joshLong145 commented on proto/registry/tx.proto
>  message MsgUpdateName {
I think we need session instances in all CRUD operations as the way i am thinking of it all operations on the chain need to be associated with a valid session

2022-04-08 15:48 UTC, joshLong145 reviewed
Tests are failing currently specifically within 
- messaging 
- registry
- whois.

2022-04-08 15:48 UTC, joshLong145 commented on x/channel/types/query.pb.go
> +		dAtA[i] = 0x12
can you add a comment on why 0x12 is always used in this iteration?

2022-04-08 15:48 UTC, joshLong145 commented on x/channel/types/query.pb.go
> +		dAtA[i] = 0x12
can you add a comment on why 0x12 is always used in this iteration?

2022-04-08 15:48 UTC, joshLong145 commented on x/channel/types/query.pb.go
> +				}
some comments on the bit shifting here would be helpful i think

2022-04-08 15:48 UTC, joshLong145 commented on x/channel/types/query.pb.go
> +		case 2:
comments on case context would be helpful here i feel

2022-04-08 16:36 UTC, ntindle commented on Taskfile.yaml
> +      - sonrd init my-node --chain-id sonr
run 
```suggestion
     - rm ~/.sonr
     - sonrd init my-node --chain-id sonr
```

2022-04-08 16:37 UTC, ntindle approved these changes

2022-04-08 17:29 UTC, prnk28 commented on proto/object/tx.proto
> +
Only for Registry module session is returned

2022-04-08 17:29 UTC, prnk28 commented on proto/registry/tx.proto
>  message MsgUpdateName {
Adding it

2022-04-08 17:34 UTC, prnk28 commented on x/channel/types/query.pb.go
> +		dAtA[i] = 0x12
This is generated code

2022-04-08 17:34 UTC, prnk28 commented on x/channel/types/query.pb.go
> +		dAtA[i] = 0x12
This is generated code

2022-04-08 17:34 UTC, prnk28 commented on x/channel/types/query.pb.go
> +		case 2:
This is generated code

2022-04-08 17:41 UTC, prnk28 commented
LFG - Full send it so we can migrate the rest

2022-04-08 19:13 UTC, prnk28 commented
Also closes issue #12

2022-04-08 20:04 UTC, joshLong145 reviewed
Looks good, confirmed endpoints work for authentication, as they did prior to migration. Approving but if you could take a look at the failing tests prior to merge it would be appreciated.

2022-04-08 20:20 UTC, mcjcloud approved these changes

2022-04-08 20:21 UTC, merged